'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var ADD_MESSAGE = exports.ADD_MESSAGE = 'ADD_MESSAGE';
var RECEIVE_MESSAGE = exports.RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';

var ADD_CHANNEL = exports.ADD_CHANNEL = 'ADD_CHANNEL';
var CHANGE_CHANNEL = exports.CHANGE_CHANNEL = 'CHANGE_CHANNEL';
var RECEIVE_CHANNEL = exports.RECEIVE_CHANNEL = 'RECEIVE_CHANNEL';

var SIGNUP_USER = exports.SIGNUP_USER = 'SIGNUP_USER';
var SIGNIN = exports.SIGNIN = 'SIGNIN';

var AUTH_LOAD = exports.AUTH_LOAD = 'AUTH_LOAD';
var AUTH_LOAD_SUCCESS = exports.AUTH_LOAD_SUCCESS = 'AUTH_LOAD_SUCCESS';
var AUTH_LOAD_FAIL = exports.AUTH_LOAD_FAIL = 'AUTH_LOAD_FAIL';

var AUTH_SIGNIN = exports.AUTH_SIGNIN = 'AUTH_SIGNIN';
var AUTH_SIGNIN_SUCCESS = exports.AUTH_SIGNIN_SUCCESS = 'AUTH_SIGNIN_SUCCESS';
var AUTH_SIGNIN_FAIL = exports.AUTH_SIGNIN_FAIL = 'AUTH_SIGNIN_FAIL';

var AUTH_SIGNOUT = exports.AUTH_SIGNOUT = 'AUTH_SIGNOUT';
var AUTH_SIGNOUT_SUCCESS = exports.AUTH_SIGNOUT_SUCCESS = 'AUTH_SIGNOUT_SUCCESS';
var AUTH_SIGNOUT_FAIL = exports.AUTH_SIGNOUT_FAIL = 'AUTH_SIGNOUT_FAIL';

var AUTH_SIGNUP_SUCCESS = exports.AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
var AUTH_SIGNUP = exports.AUTH_SIGNUP = 'AUTH_SIGNUP';
var AUTH_SIGNUP_FAIL = exports.AUTH_SIGNUP_FAIL = 'AUTH_SIGNUP_FAIL';

var TYPING = exports.TYPING = 'TYPING';
var STOP_TYPING = exports.STOP_TYPING = 'STOP_TYPING';

var ADD_USER = exports.ADD_USER = 'ADD_USER';

var REMOVE_USER_FROM_CHANNEL = exports.REMOVE_USER_FROM_CHANNEL = 'REMOVE_USER_FROM_CHANNEL';

var SAVE_USERNAME = exports.SAVE_USERNAME = 'SAVE_USERNAME';

var LOAD_MESSAGES = exports.LOAD_MESSAGES = 'LOAD_MESSAGES';
var LOAD_MESSAGES_SUCCESS = exports.LOAD_MESSAGES_SUCCESS = 'LOAD_MESSAGES_SUCCESS';
var LOAD_MESSAGES_FAIL = exports.LOAD_MESSAGES_FAIL = 'LOAD_MESSAGES_FAIL';

var LOAD_CHANNELS = exports.LOAD_CHANNELS = 'LOAD_CHANNELS';
var LOAD_CHANNELS_SUCCESS = exports.LOAD_CHANNELS_SUCCESS = 'LOAD_CHANNELS_SUCCESS';
var LOAD_CHANNELS_FAIL = exports.LOAD_CHANNELS_FAIL = 'LOAD_CHANNELS_FAIL';

var LOAD_USERSONLINE = exports.LOAD_USERSONLINE = 'LOAD_USERSONLINE';
var LOAD_USERSONLINE_SUCCESS = exports.LOAD_USERSONLINE_SUCCESS = 'LOAD_USERSONLINE_SUCCESS';
var LOAD_USERSONLINE_FAIL = exports.LOAD_USERSONLINE_FAIL = 'LOAD_USERSONLINE_FAIL';

var RECEIVE_USER = exports.RECEIVE_USER = 'RECEIVE_USER';

var START_USERNAME_VALIDATION = exports.START_USERNAME_VALIDATION = 'START_USERNAME_VALIDATION';
var USERNAME_VALIDATION_SUCCESS = exports.USERNAME_VALIDATION_SUCCESS = 'USERNAME_VALIDATION_SUCCESS';
var USERNAME_VALIDATION_FAIL = exports.USERNAME_VALIDATION_FAIL = 'USERNAME_VALIDATION_FAIL';

var LOAD_USERVALIDATION = exports.LOAD_USERVALIDATION = 'LOAD_USERVALIDATION';
var LOAD_USERVALIDATION_SUCCESS = exports.LOAD_USERVALIDATION_SUCCESS = 'LOAD_USERVALIDATION_SUCCESS';
var LOAD_USERVALIDATION_FAIL = exports.LOAD_USERVALIDATION_FAIL = 'LOAD_USERVALIDATION_FAIL';

var RECEIVE_MESSAGES = exports.RECEIVE_MESSAGES = 'RECEIVE_MESSAGES';

var CHANGE_IS_MOBILE = exports.CHANGE_IS_MOBILE = 'CHANGE_IS_MOBILE';
var CHANGE_WIDTH_AND_HEIGHT = exports.CHANGE_WIDTH_AND_HEIGHT = 'CHANGE_WIDTH_AND_HEIGHT';

var RECEIVE_SOCKET = exports.RECEIVE_SOCKET = 'RECEIVE_SOCKET';